### ISSUE TITLE
"Living" -> "Live"[I18N] 

### ISSUE THREAD

**Issue by VaporMoon** [YunzheZJU/holo-schedule#22]
**Note: You are filing an issue on the translation quality. You are also welcomed to open a pull-request if possible to directly contribute to this project!**

**What are your changes?**
Just a small English correction of "Living" -> "Live"

**Where can we find the texts to change?**
Steps to find the text:
1. Open Holo-Schedule

**Additional context**
"Living" is not quite the right word to use here in English.

**Comment by YunzheZJU** [comment]
Thank you very much for your suggestion!
I am proposing a commit to resolve this issue.

**Comment by YunzheZJU** [comment]
Resolved in fb474ad0.
I am going to close this issue because your suggestions have been adopted and merged into the master branch successfully.

A new version of HoloSchedule has been released and it may take another few days to pass the review from the extension stores.

Feel free to open another issue if you have any question!
