### ISSUE TITLE
Include notification for "Hololive" channel

### ISSUE THREAD

**Issue by oOBoomberOo** [YunzheZJU/holo-schedule#35]
Sometimes hololive members will stream on the [official channel](https://www.youtube.com/channel/UCJFZiqLMntJufDCHc6bQixg) so I feel that we should have an option to be notified of these streams as well.

**Comment by YunzheZJU** [comment]
I agree with you.
To let users be notified by the members' activities on this channel, I come out with two ways:
1. Add the 'Hololive' channel as a special 'member'. It would be grouped into a new group named 'Others' in 'Advanced Settings' page, other than the existing 'Hololive', 'INoNaKa MUSIC', 'Hololive China', etc. The short is that this channel is a 'hack' and is not elegant... 
2. Parse all new lives on 'Hololive' channel into personal live (infering from title, description, or even the cover) and split them into the members' personal live notification. This should be powerful and we can even use it on collaboration lives where multiple members are streaming on a single channel. However we don't have a so stable algorithm to use to extract the collaboration info. There are technical obstacles.

Since more and more users are looking for the notification of lives on 'Hololive' channel, I will take the first method to meet our needs first.

*PS: Taking [the latest live](https://www.youtube.com/watch?v=dpEM6MyUjx8) from 'Hololive' channel as an example, anyone who has an idea on extracting collaboration infos programmatically are welcome to share your thoughts here! (even if this issue has been closed)*

**Comment by oOBoomberOo** [comment]
I don't think the 1) method is as bad as you make it to be, speaking as myself, I would totally expect that I will get notified from the official channel instead of splitting into multiple members. So don't worry too much about it 👍

**Comment by YunzheZJU** [comment]
Resolved in 0a1367cf.
This issue has been automatially closed because your suggestions have been adopted and merged into the master branch successfully.

A new version of HoloSchedule has been released and it may take another few days to pass the review from the extension stores.

Feel free to open another issue if you have any question! Thank you again for your suggestion!
