### ISSUE TITLE
[FEATURE] Dark mode

### ISSUE THREAD

**Issue by elementybt** [YunzheZJU/holo-schedule#47]
Thank you for this extension, it's excellent. Just wanted to suggest adding an option to switch to a dark mode if possible.

**Comment by YunzheZJU** [comment]
Thank you for your suggestion. As number of users is growing, I think this is necessary.
I plan to use CSS media query to detect user's preferred theme and apply it to the pages automatically.

**Comment by YunzheZJU** [comment]
Hi! I have made changes to support dark mode. It will detect your prefered theme and apply color changes automatically.

 - You can get a screenshot preview from #48.
 - You can as well get a glance at how to change system themes and browser outlooks (for Chrome, also applies to Firefox) at https://support.google.com/chrome/answer/9275525?co=GENIE.Platform%3DDesktop.

Hope you will like it!

**Comment by YunzheZJU** [comment]
Resolved in 0820de23.
This issue has been automatially closed because your suggestions have been adopted and merged into the master branch successfully.

A new version of HoloSchedule has been released and it may take another few days to pass the review from the extension stores.

Feel free to open another issue if you have any question! Thank you again for your suggestion!
