### ISSUE TITLE
[I18N] translate store page description to Japanese

### ISSUE THREAD

**Issue by is984** [YunzheZJU/holo-schedule#56]
I am not very good at English, so I apologize in advance.

**Note: You are filing an issue on the translation quality. You are also welcomed to open a pull-request if possible to directly contribute to this project!**

**What are your changes?**

---Contents start---

—— Keep in touch with Hololive. 

ホロライブの配信スケジュールを表示するブラウザ拡張です。ゲリラ配信にも対応しています。
このブラウザ拡張は[ ホロジュール](https://schedule.hololive.tv/lives)を使いやすくすることを目的としています。<- I have no confidence this Line. Need Help->

現在、ホロジュールの基本機能が実装されています。<- I have no confidence this Line. Need Help->

-  配信中のライブ一覧表示
-  今後7日分の配信予定の表示
-  過去3日間の配信の表示
-  配信のリマインダ
-  ゲリラ配信開始時のデスクトップ通知機能
-  日本語、英語、中国語（簡体字）の3言語に対応
-  ... より、面白いものを開発中です!   <- I have no confidence this Line. Need Help->

何か、質問や提案などがあれば help@holo.devにご連絡ください。

このブラウザ拡張が素晴らしいと感じたら、[Github プロジェクト](https://github.com/YunzheZJU/holo-schedule)にスターを付けてください。

---Contents End-----

**Where can we find the texts to change?**
This part in store page.
![image](https://user-images.githubusercontent.com/22042489/110573378-83252e80-819e-11eb-8e2a-1ba9cd4395d4.png)

**Additional context**
It's in at least passable Japanese.
However, some sentences may not have been translated correctly.

I'm sorry if i have the wrong kind of ticket.

**Comment by YunzheZJU** [comment]
Whatever you are good at English or not, any contribution is valuable and welcomed! Thank you! あなたが英語が得意であろうとなかろうと、どんな貢献も価値があり、歓迎されます！ ありがとうございました！

I think this line is translated into a different meaning: この行は別の意味に翻訳されていると思います。
```
This extension expects to provide a similar, or even better, experience as hololive schedule
このブラウザ拡張は ホロジュールを使いやすくすることを目的としています。
```
However, [Google translates](https://translate.google.com/?sl=auto&tl=ja&text=This%20extension%20expects%20to%20provide%20a%20similar%2C%20or%20even%20better%2C%20experience%20as%20hololive%20schedule&op=translate) it into: ただし、Googleはそれを次のように翻訳します。
```
この拡張機能は、ホロジュールと同様の、またはさらに優れたエクスペリエンスを提供することを期待しています。
```
Maybe Google's translation is more accurate...? :/ 多分Googleの翻訳はもっと正確です...？ :/

Also, I think this sentence should not be related to `ホロジュール`: また、この文は「ホロジュール」に関連するべきではないと思います。
```
This release contains the basic functionality of holo-schedule, including:
現在、ホロジュールの基本機能が実装されています。
```
`holo-schedule` here refers to this project/this extension itself, instead of [the official one](https://schedule.hololive.tv/lives). ここでの `holo-schedule`は、[公式のもの]ではなく、このプロジェクト/この拡張機能自体を指します。

If we can re-considerate the translations of the two lines above, I think it would be OK to accept and publish them to the store! 上記の2行の翻訳を再考できれば、それを受け入れてストアに公開しても大丈夫だと思います！ 😃

**Comment by is984** [comment]
Thanks for pointing that out.

Based on what you pointed out, I think the translation would be as follows.

I completely misunderstood the meaning of the sentence. I'm sorry.
```
This extension expects to provide a similar, or even better, experience as hololive schedule
このブラウザ拡張は、ホロジュールと同等かそれ以上に優れたユーザーエクスペリエンスが期待されています。
```


I was confusing holo-schedule with hololive schedule.
If holo-schedule is referring to this browser extension, I think the translation would be as follows
```
This release contains the basic functionality of holo-schedule, including:
現在、このブラウザ拡張には以下の基本的な機能が含まれます。
```

**Comment by YunzheZJU** [comment]
> I completely misunderstood the meaning of the sentence. I'm sorry.

That's OK! English is not my native language so it should be my fault to write such sentence which causes misunderstanding. Thank you for correcting them!

If there isn't any more question, I will update the store page as follows:
![0](https://user-images.githubusercontent.com/23452609/110802980-b0b2ca80-82b9-11eb-8150-915f79657b2a.png)

よろしいですか？

**Comment by is984** [comment]
OK, it looks fine.
Thank you for some advice.

**Comment by YunzheZJU** [comment]
I've updated the store pages but it may take some time to reflect on Chrome's store. [Mozilla's one](https://addons.mozilla.org/ja/firefox/addon/holo-schedule/) is the latest version now.

I want to say a BIG 'Thank you!' to you because your translation will make HoloSchedule be exposed to and attract more Japanese users! THANK YOU!!!!!!!!!!!!!!!!!!!!!

(I will resolve this issue after I found Chrome's store page has been updated publicly.)

**Comment by is984** [comment]
I am honored to be of service.

One thing seems to be wrong with the display.
"ホロジュール" is not a hyperlink, and the word "hololive schedule" appears to be included in the translation.
![image](https://user-images.githubusercontent.com/22042489/111017015-684bf780-83f4-11eb-8114-78fe32b5596f.png)

**Comment by YunzheZJU** [comment]
Oh, you're right! I'll correct it as soon as possible! Thank you very much!

**Comment by YunzheZJU** [comment]
Since [Chrome's store page](https://chrome.google.com/webstore/detail/holoschedule/fjicegllhddldnnkgfefblholeegpcad?hl=ja) has been updated, I will close this issue.

Thank you again for your contribution!
