### ISSUE TITLE
Switch Language Error/Unrecognized

### ISSUE THREAD

**Issue by samdotxml** [YunzheZJU/holo-schedule#64]
Hello

I've done a fork of holo-schedule. I added the German language and everything works perfectly fine. I encountered one issue. I wanted to ask how to fix before ill make a pull request. When im the selection menu of the languages the DE language doesn't get displayed correctly when another language is selected. When it is selected, it displays correctly.

**When for example English is selected:**
![o75pQxo6iR](https://user-images.githubusercontent.com/80579142/114621990-aff0c800-9cad-11eb-85f3-b6c15547bd8b.png)

**When German is selected:**
![firefox_rt6B9YdiUK](https://user-images.githubusercontent.com/80579142/114622015-baab5d00-9cad-11eb-8bbc-435acf9085de.png)

Im not a js expert. But i would be very happy for a quick explaination how to fix this.

Thanks in advance and i will be (hopefully) contributing my language to the repo

**Comment by YunzheZJU** [comment]
Hi! You have done a great work!

This issue is caused for the reason that when you are using 'en', for example, there is no translation for the key 'app.settings.language.locales,de' in the en locale. So it is key to modify other locale files when adding a new locale.

I admit that solution is not explicit and feel great sorry for your confusion.

I have pushed a new branch named [new-locale-bootstrap](https://github.com/YunzheZJU/holo-schedule/commit/fc14b80163f951e5bcd2079604f1a27f4c09ac4b#diff-35d0778468e56151d6c5689d7080441173fb80a5429ae7cf5ae4a1b9afae6f6eR44) which includes all the necessary files to be modified. You can work on this branch and hope it will help you.

**Comment by samdotxml** [comment]
Thank you very much. I just woke up. Ill have a Coffee and check out the branch!
